### ISSUE TITLE
Compile Error with boost 1.58 and gcc 5.2.1 (Debian sid)

### ISSUE THREAD

**Issue by giggls** [Oslandia/SFCGAL#106]
Hello,

with the current work in progress gcc5 Migration of Debian GNU/Linux sfcgal does no longer build.

Here is what I get:

    cd /«PKGBUILDDIR»/obj-i586-linux-gnu/src && /usr/bin/c++   -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DCGAL_INTERSECTION_VERSION=1 -DSFCGAL_BUILD_SHARED -DSFCGAL_EXPORTS -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -Wall -Wextra -Wno-long-long -pedantic -Wpointer-arith -Wcast-align -Wcast-qual -Wno-overloaded-virtual -Wformat=2 -Winit-self -Wmissing-include-dirs -Wwrite-strings -Wno-error=undef -fPIC -I/«PKGBUILDDIR»/obj-i586-linux-gnu/include -I/«PKGBUILDDIR»/patches/CGAL-4.3 -isystem /usr/include/i386-linux-gnu    -o CMakeFiles/SFCGAL.dir/algorithm/union.cpp.o -c /«PKGBUILDDIR»/src/algorithm/union.cpp
    In file included from /usr/include/boost/tuple/tuple.hpp:24:0,
                     from /usr/include/boost/exception/info_tuple.hpp:16,
                     from /usr/include/boost/exception/all.hpp:20,
                     from /«PKGBUILDDIR»/obj-i586-linux-gnu/include/SFCGAL/Exception.h:28,
                     from /«PKGBUILDDIR»/obj-i586-linux-gnu/include/SFCGAL/algorithm/differencePrimitives.h:24,
                     from /«PKGBUILDDIR»/src/algorithm/union.cpp:21:
    /usr/include/boost/variant/get.hpp: In instantiation of 'typename boost::add_reference<T>::type boost::strict_get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = CGAL::Point_2<CGAL::Epeck>&; T0 = CGAL::Point_2<CGAL::Epeck>; T1 = SFCGAL::algorithm::Segment_d<2>; T2 = SFCGAL::algorithm::Surface_d<2>; T3 = SFCGAL::detail::NoVolume; T4 = SFCGAL::algorithm::EmptyPrimitive; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = CGAL::Point_2<CGAL::Epeck>&]':
    /usr/include/boost/variant/get.hpp:284:25:   required from 'typename boost::add_reference<T>::type boost::get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = CGAL::Point_2<CGAL::Epeck>&; T0 = CGAL::Point_2<CGAL::Epeck>; T1 = SFCGAL::algorithm::Segment_d<2>; T2 = SFCGAL::algorithm::Surface_d<2>; T3 = SFCGAL::detail::NoVolume; T4 = SFCGAL::algorithm::EmptyPrimitive; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = CGAL::Point_2<CGAL::Epeck>&]'
    /«PKGBUILDDIR»/src/algorithm/union.cpp:392:65:   required from 'typename SFCGAL::detail::Point_d<Dim>::Type& SFCGAL::algorithm::Handle<Dim>::asPoint() [with int Dim = 2; typename SFCGAL::detail::Point_d<Dim>::Type = CGAL::Point_2<CGAL::Epeck>]'
    /«PKGBUILDDIR»/src/algorithm/union.cpp:508:34:   required from here
    /usr/include/boost/variant/get.hpp:178:5: error: invalid application of 'sizeof' to incomplete type 'boost::STATIC_ASSERTION_FAILURE<false>'
         BOOST_STATIC_ASSERT_MSG(
         ^

See also:
https://buildd.debian.org/status/fetch.php?pkg=sfcgal&arch=i386&ver=1.1.0-2&stamp=1440195731

**Comment by sanak** [comment]
@giggls
I think that above error relates to #103.
Are you using the latest master branch which include #104 fix ?

**Comment by giggls** [comment]
ACK using fix https://github.com/Oslandia/SFCGAL/pull/104 everything seems to work again.

I can not package upstream/master as Debian is all about released Versions I#m still stuck with 1.1.0 as this is the latest version announced on https://github.com/Oslandia/SFCGAL/releases

**Comment by vmora** [comment]
@giggls is there a deadline on the debian side ? 

There is one simple fix coming in master (#109) and maybe @strk wants to improve the approx medial axis, but we should be able to release 1.2 pretty fast.

BTW: thank for packaging sfcgal.

**Comment by giggls** [comment]
No deadline. Just this libstdc++ transition which will require to recompile all c++ packages.

However, there are 2 minor problems with tests regarding the debian package. I had to disable running tests during build at all because all the provided tests use the library installed on the system instead of the one just build. The other problem is with test-style-SFCGAL.sh . I suppose this is a problem witch a slightly different astyle command. Looking at the output I get something like this:
128,129c128
<     int operator()( const Coordinate::Empty& ) const
<     {
---
>     int operator()( const Coordinate::Empty& ) const {

Sven

**Comment by mhugo** [comment]
The style test has just been disabled in 24db3b8a2 since it is not robust enough

> I had to disable running tests during build at all because all the provided tests use the library installed on the system instead of the one just build.

Hmmm, this is not good. We should find a way to find this before releasing. Thanks

**Comment by vmora** [comment]
Weird, in CMakeLists.txt:

    add_test( unit-test ${CMAKE_CURRENT_BINARY_DIR}/unit-test-SFCGAL )

And when I run ctest:

    1: Test command: /home/vmo/SFCGAL/build/test/unit/unit-test-SFCGAL

So a LD_LIBRARY_PATH problem ?

   $ ctest -V

**Comment by giggls** [comment]
Original discussion is here:
https://lists.debian.org/debian-gis/2015/06/msg00032.html
Enabling the SFCGAL_BUILD_TESTS option adds additional tests, but they
all fail because they cannot find libSFCGAL.so.1. The tests need to be
fixed to use the just built library to run.

**Comment by mhugo** [comment]
@giggls Hmmm ... I don't understand. My tests are linked to the local libSFCGAL.so.1
ldd ./test/unit/unit-test-SFCGAL | grep SFCGAL
	libSFCGAL.so.1 => /home/hme/src/SFCGAL/build/src/libSFCGAL.so.1 (0x00007f56a1a9e000)

**Comment by giggls** [comment]
obj-x86_64-linux-gnu/ (master *) > ldd ./test/unit/unit-test-SFCGAL | grep SFCGAL
	libSFCGAL.so.1 => /usr/lib/x86_64-linux-gnu/libSFCGAL.so.1 (0x00007f878fdf4000)

Could this be related to CMAKE_SKIP_RPATH=ON Option?

https://wiki.debian.org/RpathIssue

**Comment by mhugo** [comment]
Indeed. If you skip the rpath, then the .so cannot be found in the build directory. It has to be found system-wide.
This is equivalent to running "chrpath -d" on executables

**Comment by vmora** [comment]
In the build script, setting the LD_LIBRARY_PATH with build directory first should fix the problem.

**Comment by giggls** [comment]
OK, I will tyr to disable CMAKE_SKIP_RPATH and remove rpath later on.

**Comment by mhugo** [comment]
@giggls Just to let you know the 1.2 has been released

**Comment by giggls** [comment]
Hm garden-test does not seem to work here:

```
3/3 Test #3: garden-test ......................***Failed  205.34 sec

error 1 in ( void )algorithm::straightSkeleton( *geom1 ) ;: CGAL ERROR: assertion violation!
Expr: is_finite(d)
File: /usr/include/CGAL/Interval_nt.h
Line: 122
error with valid geometry MULTIPOLYGON((()),(()))

error 2 in ( void )algorithm::straightSkeleton( *geom1 ) ;: CGAL ERROR: assertion violation!
Expr: is_finite(d)
File: /usr/include/CGAL/Interval_nt.h
Line: 122
error with valid geometry MULTIPOLYGON(((-3/1 -1/1,-1/1 -1/1,-1/1 1/1,-3/1 1/1,-3/1 -1/1)),(()))

error 3 in ( void )algorithm::straightSkeleton( *geom1 ) ;: CGAL ERROR: assertion violation!
Expr: is_finite(d)
File: /usr/include/CGAL/Interval_nt.h
Line: 122
error with valid geometry MULTIPOLYGON((()),(()))
Missing implementations
    Intersection does not support polygon with connected rings
    distance(Point,Solid) is not implemented
    distance(Solid,GeometryCollection) is not implemented
    distance(Solid,LineString) is not implemented
    distance(Solid,MultiLineString) is not implemented
    distance(Solid,MultiPoint) is not implemented
    distance(Solid,MultiPolygon) is not implemented
    distance(Solid,Point) is not implemented
    distance(Solid,Polygon) is not implemented
    distance(Solid,PolyhedralSurface) is not implemented
    distance(Solid,Solid) is not implemented
    distance(Solid,Triangle) is not implemented
    distance(Solid,TriangulatedSurface) is not implemented
    straight skeleton of Polygon with touching interior rings is not implemented


**** 3 test failed

```

Will I need libcgal 4.6.2?

**Comment by mhugo** [comment]
@giggls Strange. I've just tested again but cannot reproduce.
Builds on travis are ok as well https://travis-ci.org/Oslandia/SFCGAL

**Comment by giggls** [comment]
Looks like I found the problem but I can not really classify it.
For some reason dh_auto_configure will set -DCMAKE_BUILD_TYPE=None which will for cause the above trouble with sfcgal.

**Comment by vmora** [comment]
Hi @giggls, Are you sure the option is passed explicitly (None) ? Because None is the default cmake build type (wich is not really smart IMO).

**Comment by giggls** [comment]
Jepp, looks like "None"  is passed explicitly. Unfortunately I did not yet figure out how to change this to RelWithDebInfo
