### ISSUE TITLE
Links on www.sfcgal.org are out of date or broken

### ISSUE THREAD

**Issue by robe2** [Oslandia/SFCGAL#107]
1) Shouldn't the tar and zip source tar balls on www.sfcgal.org point at least stable release (1.1.0 soon to be 1.2.0).  It still points at 1.0.5.

2) Now this one is a little weird might be some funky redirection.
If I go to http://www.sfcgal.org/  and then click on development link
and then click on Issues (at least in firefox) - it takes me http://www.sfcgal.org/ (with that shows a blank page).

However if instead of clicking, I right-mouse open in new window.  Then it correctly takes me to issues.

**Comment by mhugo** [comment]
1) Should now be fixed, thanks
2) Confirmed ... but can't understand why ...

**Comment by mhugo** [comment]
Fixed
