### ISSUE TITLE
ST_Extrude (in PostGIS) of M geometries looses M

### ISSUE THREAD

**Issue by robe2** [Oslandia/SFCGAL#110]
I think the issue we have ticketed at https://trac.osgeo.org/postgis/ticket/2756  is an SFCGAL issue.
So switched milestone to SFCGAL.  Let me know if this can be fixed or not. I can mark it as a no-fix and just put a warning in docs.  It's a rare use I think anyway.

```
SELECT ST_AsText(ST_Extrude('LINESTRING M (-10 50 1,50 -10 1)'::geometry, 20.1,20.1,20.1) );

```

Gives:

```

POLYHEDRALSURFACE Z (((-10 50 0,50 -10 0,70.1 10.1 20.1,10.1 70.1 20.1,-10 50 0)))

```

**Comment by mhugo** [comment]
There is no common rule of what is expected when creating a new M (copy it ? multiply it by the length of the extrusion vector ?). So we drop it. It should be documented this way indeed :)

**Comment by danielcu888** [comment]
@mhugo I don't mind doing this if you wish to assign it to me.

**Comment by danielcu888** [comment]
Thanks, @lbartoletti I'll get started on this today.

**Comment by danielcu888** [comment]
@lbartoletti I have submitted PR 228 to address this issue.

**Comment by danielcu888** [comment]
@lbartoletti this can now be resolved I think.
