### ISSUE TITLE
SFCGAL 1.2.1 release invalid -- patch version was not changed

### ISSUE THREAD

**Issue by robe2** [Oslandia/SFCGAL#116]
The  SFCGAL 1.2.1 release (and root) still have SFCGAL version reading 1.2.0

The CMakeLists file was never changed to reflect the new version.

https://github.com/Oslandia/SFCGAL/blob/master/CMakeLists.txt

**Comment by mhugo** [comment]
True ... sorry for that. I'll release a 1.2.2

**Comment by mhugo** [comment]
SFCGAL 1.2.2 is out wich fixed CMakeLists.txt

**Comment by robe2** [comment]
Now I'm going to be a nitpick -- your release notes don't mention that this very important issue was patched - #111

**Comment by strk** [comment]
also, the 1.2.3 milestone should be added and 1.2.2 removed (here on github)

**Comment by strk** [comment]
I've added the missing item in a commit to master (f385553a1801efc18e0da691761901bea9148fc0)

**Comment by strk** [comment]
and I've also closed 1.2.2 milestone and created 1.2.3

**Comment by mhugo** [comment]
@strk thanks. I've updated the github release notes
