### ISSUE TITLE
SFCGAL fails to build against boost 1.60

### ISSUE THREAD

**Issue by pjduplooy** [Oslandia/SFCGAL#119]
Hi guys

Happy new year!

I have a small problem

I am running Manjaro Linux (Arch Linux spin), which has gcc 5.3, boost 1.60, and libstdc++ 3.3.6
Building SFCGAL gives the following errors:

  5%] Building CXX object src/CMakeFiles/SFCGAL.dir/algorithm/collectionHomogenize.cpp.o
In file included from /usr/include/CGAL/assertions.h:36:0,
                 from /usr/include/CGAL/basic.h:42,
                 from /usr/include/CGAL/Bbox_2.h:27,
                 from /home/pieter/abs/sfcgal/src/SFCGAL-1.2.2/include/SFCGAL/Envelope.h:27,
                 from /home/pieter/abs/sfcgal/src/SFCGAL-1.2.2/src/algorithm/straightSkeleton.cpp:23:
/usr/include/boost/graph/adjacency_matrix.hpp:446:5: error: ‘ice_not’ is not a member of ‘boost::type_traits’
     BOOST_STATIC_ASSERT(type_traits::ice_not<(is_same<Directed, bidirectionalS>::value)>::value);
     ^
/usr/include/boost/graph/adjacency_matrix.hpp:446:5: error: ‘::value’ has not been declared
     BOOST_STATIC_ASSERT(type_traits::ice_not<(is_same<Directed, bidirectionalS>::value)>::value);
     ^
/usr/include/boost/graph/adjacency_matrix.hpp:446:5: note: suggested alternative:
In file included from /usr/include/boost/bind.hpp:22:0,
                 from /usr/include/CGAL/Straight_skeleton_2/Straight_skeleton_builder_2_impl.h:22,
                 from /usr/include/CGAL/Straight_skeleton_builder_2.h:930,
                 from /usr/include/CGAL/create_straight_skeleton_2.h:23,
                 from /usr/include/CGAL/create_straight_skeleton_from_polygon_with_holes_2.h:23,
                 from /home/pieter/abs/sfcgal/src/SFCGAL-1.2.2/src/algorithm/straightSkeleton.cpp:37:
/usr/include/boost/bind/bind.hpp:118:25: note:   ‘boost::_bi::value’
 template<class T> class value
                         ^
src/CMakeFiles/SFCGAL.dir/build.make:854: recipe for target 'src/CMakeFiles/SFCGAL.dir/algorithm/straightSkeleton.cpp.o' failed
make[2]: *** [src/CMakeFiles/SFCGAL.dir/algorithm/straightSkeleton.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:141: recipe for target 'src/CMakeFiles/SFCGAL.dir/all' failed
make[1]: *** [src/CMakeFiles/SFCGAL.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

I cannot downgrade to 1.59 as this breaks the OS.

Any help?

Pieter

**Comment by pjduplooy** [comment]
Ok, managed to downgrade my system to boost 1.59, but please check compilation against 1.60

**Comment by saultdon** [comment]
Same error running Arch Linux 64-bit (w/ boost 1.60.0)

**Comment by mborne** [comment]
Hi!

The following error seems to be related to boost/graph/adjacency_matrix and boost/type_traits :

/usr/include/boost/graph/adjacency_matrix.hpp:446:5: error: ‘ice_not’ is not a member of ‘boost::type_traits’

"boost/graph/adjacency_matrix.hpp" includes "boost/type_traits.hpp". Since 1.60, "boost/type_traits.hpp" doesn't seem to include "boost/type_traits/ice.hpp":

http://www.boost.org/doc/libs/1_59_0/boost/type_traits.hpp
http://www.boost.org/doc/libs/1_60_0/boost/type_traits.hpp

I'll try to add the following line in boost/graph/adjacency_matrix.hpp in order to confirm that 

<pre>
#include boost/type_traits/ice.hpp
</pre>

**Comment by mborne** [comment]
Corresponding boost issue : https://svn.boost.org/trac/boost/ticket/11880

**Comment by mhugo** [comment]
Fixed on master. 1.3 release coming soon
