### ISSUE TITLE
SFCGAL/Grid.h: No such file or directory

### ISSUE THREAD

**Issue by jiapei100** [Oslandia/SFCGAL#134]
Environment:

Ubuntu 16.04.1+GCC/G++ 5.4.0

I believe this issue is just from SFCGAL itself.

SFCGAL/example/SFCGAL-asc2osg/main.cpp:26:25: fatal error: SFCGAL/Grid.h: No such file or directory

Any suggestions?
Pei

**Comment by mhugo** [comment]
Fixed in b4dc0b2
