### ISSUE TITLE
Robustness issues when writing to postgis

### ISSUE THREAD

**Issue by econoraptor** [Oslandia/SFCGAL#135]
I'm trying to write cgal geometry to postgis and use sfcgal to perform operations, but it seems the loss of precision is causing some errors with validity checks.  

For instance, I have converted some cgal epeck vertices to sfcgal R^3 polygons in C++, ran sfcgal::isvalid on the polygons, and written them to a postgis column with a ST_IsPlanar check constraint.  However, when I try to actually perform an sfcgal operation on the polygons in postgis I get a validity error saying the points aren't coplanar.

I have tried using SFCGAL::detail::io::WktWriter as well as just using point().exact().to_double() directly, but it seems that postgis just coerces or truncates the input.

Is there any way to write exact cgal geometry to postgis and have the geometry remain valid so that it can be used by sfcgal?

**Comment by econoraptor** [comment]
I've now tried building postgis and sfcgal from source with SFCGAL_CHECK_VALIDITY=OFF as well as a couple other things, but nothing seems to be working.  Here's a reproduction:

You'll notice IsPlanar is true, but ST_3DArea raises an error saying the points aren't coplanar.

```
CREATE TABLE polygon_test();
SELECT AddGeometryColumn('polygon_test', 'geom', 4326, 'POLYGONZ', 3);
INSERT INTO polygon_test (geom) VALUES(ST_GeomFromText('POLYGON Z ((-2456.65849662024 -494.251393883276 412,-2486.7786660429 -413.696999618586 412,-2486.77945264572 -413.696623334753 354,-2456.65889152129 -494.252065179804 354,-2456.65849662024 -494.251393883276 412))', 4326));
SELECT ST_IsPlanar(geom) FROM polygon_test;
 
 
SELECT ST_3DArea(geom) FROM polygon_test;
```

**Comment by mhugo** [comment]
Hi @econoraptor.
Geometries in PostGIS are stored with coordinates as double precision floating point numbers. So you can easily find exact coordinates that are approximated when converted into double. We would need a specialized geometry type in PostGIS to circumvent this ...

I'll have a look at the other problem

**Comment by mhugo** [comment]
There was a bug in ST_IsPlanar, it called hasPlane3D. It now calls isPlane3D (e61c52763)
It will then return false for your polygon.
