### ISSUE TITLE
Allow splitting up OpenSceneGraph dependancy into different package when viewer is built

### ISSUE THREAD

**Issue by Komzpa** [Oslandia/SFCGAL#136]
Since PostGIS 2.2 SFCGAL is a dependancy.

In Debian / Ubuntu SFCGAL is built with viewer enabled.
This means PostGIS required /usr/lib/x86_64-linux-gnu/libSFCGAL.so.1 gets a dependancy on /usr/lib/x86_64-linux-gnu/libosg.so.100 which brings the whole universe into the system when installed.

This is particularly painful in constrained environments, e.g. Docker containers, where space usage rapidly grows from ~200mb for Debian+Postgres to ~1Gb for PostGIS+SFCGAL+OpenSceneGraph.

Please make a way to build this package so that when viewer is built but packaged separately, the libSFCGAL.so does not get dependancy for OSG.

Thanks.

**Comment by mhugo** [comment]
That should be fixed in ec5b86aee44

**Comment by Komzpa** [comment]
@mhugo 

Issue here is Debian is going to continue building "full' version of SFCGAL, with viewer.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838036

After the source package is built, its binaries are packaged separately, and dependencies for packages are calculated based on libraries they require.

So, issue is not about building SFCGAL without osg support, but building it _with_ sfcgal support splitting the support itself into separate wrapper/library/binary, that libSFCGAL itself won't depend on.

**Comment by mhugo** [comment]
@Komzpa 
I've added compilation targets to compile a libSFCGAL-osg.so that includes functionalities that require OSG. libSFCGAL.so does not depend anymore on OSG libraries.
Is it better ?

**Comment by Komzpa** [comment]
@mhugo thanks! Should be much better.

**Comment by Komzpa** [comment]
I've informed Sebastiaan Couwenberg about this being fixed, hope they will share any details/issues with split packaging left if there are any.

**Comment by sebastic** [comment]
The viewer is no longer included in SFCGAL, but OpenSceneGraph support is still available. I even fixed that after the viewer was removed, see #126.

Moving the OSG support to a separate library is a good option to not have its dependencies in the standard libsfcgal dependency chain. The Debian package will be updated accordingly when these changes are included in the next release.

**Comment by Komzpa** [comment]
Hello, is there anything that can be done for this to be delivered?

**Comment by rnz** [comment]
Please fix this:
`# apt-get install -t jessie-pgdg postgresql-9.6-postgis-2.3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  fonts-droid ghostscript gsfonts i965-va-driver libaacs0 libarmadillo4 libarpack2 libasound2 libasound2-data libasyncns0 libaudio2 libavcodec56 libavdevice55 libavformat56 libavresample2 libavutil54 libblas-common libblas3
  libbluray1 libboost-chrono1.55.0 libboost-date-time1.55.0 libboost-filesystem1.55.0 libboost-program-options1.55.0 libboost-serialization1.55.0 libboost-system1.55.0 libboost-test1.55.0 libboost-thread1.55.0
  libboost-timer1.55.0 libcdio-cdda1 libcdio-paranoia1 libcdio13 libcgal10 libcoin80 libcroco3 libcupsfilters1 libcupsimage2 libdap11 libdapclient3 libdapserver7 libdc1394-22 libdrm-intel1 libepsilon1 libfaad2 libflac8 libfreexl1
  libgdal1h libgeos-3.4.2 libgeos-c1 libgfortran3 libgif4 libgomp1 libgraphicsmagick3 libgs9 libgs9-common libgsm1 libhdf4-0-alt libhdf5-8 libijs-0.35 libiso9660-8 libjack-jackd2-0 libjbig2dec0 libkml0 liblapack3 liblcms2-2
  libldb1 libltdl7 liblwgeom-2.3-0 libmad0 libmng1 libmodplug1 libmp3lame0 libmpcdec6 libmysqlclient18 libnetcdfc7 libntdb1 libodbc1 libogdi3.2 libogg0 libopenjpeg5 libopenscenegraph100 libopenthreads20 libopus0 liborc-0.4-0
  libpaper-utils libpaper1 libpciaccess0 libpoppler-glib8 libpoppler46 libpostproc52 libproj0 libpulse0 libpython2.7 libqt4-opengl libqtcore4 libqtgui4 libquadmath0 libraw1394-11 librsvg2-2 librsvg2-common libsamplerate0
  libschroedinger-1.0-0 libsfcgal1 libsmbclient libsndfile1 libspatialite5 libspeex1 libswscale3 libtalloc2 libtdb1 libtevent0 libtheora0 liburiparser1 libusb-1.0-0 libv4l-0 libv4lconvert0 libva1 libvcdinfo0 libvdpau1 libvorbis0a
  libvorbisenc2 libvpx1 libwavpack1 libwbclient0 libwebp5 libwmf0.2-7 libx264-142 libxerces-c3.1 libxine2 libxine2-bin libxine2-doc libxine2-ffmpeg libxine2-misc-plugins libxine2-plugins libxvidcore4 mysql-common odbcinst
  odbcinst1debian2 poppler-data postgresql-9.6-postgis-2.3-scripts proj-bin proj-data python-talloc qtcore4-l10n samba-libs va-driver-all vdpau-va-driver
Suggested packages:
  ghostscript-x libasound2-plugins alsa-utils nas libbluray-bdj libopenal0a libsimage-dev graphicsmagick-dbg libhdf4-doc libhdf4-alt-dev hdf4-tools libnetcdf4 jackd2 liblcms2-utils libmyodbc odbc-postgresql tdsodbc unixodbc-bin
  ogdi-bin opus-tools pciutils pulseaudio qt4-qtconfig libraw1394-doc librsvg2-bin speex nvidia-vdpau-driver vdpau-driver gxine xine-ui poppler-utils fonts-japanese-mincho fonts-ipafont-mincho fonts-japanese-gothic
  fonts-ipafont-gothic fonts-arphic-ukai fonts-arphic-uming fonts-nanum postgis xvba-va-driver
The following NEW packages will be installed:
  fonts-droid ghostscript gsfonts i965-va-driver libaacs0 libarmadillo4 libarpack2 libasound2 libasound2-data libasyncns0 libaudio2 libavcodec56 libavdevice55 libavformat56 libavresample2 libavutil54 libblas-common libblas3
  libbluray1 libboost-chrono1.55.0 libboost-date-time1.55.0 libboost-filesystem1.55.0 libboost-program-options1.55.0 libboost-serialization1.55.0 libboost-system1.55.0 libboost-test1.55.0 libboost-thread1.55.0
  libboost-timer1.55.0 libcdio-cdda1 libcdio-paranoia1 libcdio13 libcgal10 libcoin80 libcroco3 libcupsfilters1 libcupsimage2 libdap11 libdapclient3 libdapserver7 libdc1394-22 libdrm-intel1 libepsilon1 libfaad2 libflac8 libfreexl1
  libgdal1h libgeos-3.4.2 libgeos-c1 libgfortran3 libgif4 libgomp1 libgraphicsmagick3 libgs9 libgs9-common libgsm1 libhdf4-0-alt libhdf5-8 libijs-0.35 libiso9660-8 libjack-jackd2-0 libjbig2dec0 libkml0 liblapack3 liblcms2-2
  libldb1 libltdl7 liblwgeom-2.3-0 libmad0 libmng1 libmodplug1 libmp3lame0 libmpcdec6 libmysqlclient18 libnetcdfc7 libntdb1 libodbc1 libogdi3.2 libogg0 libopenjpeg5 libopenscenegraph100 libopenthreads20 libopus0 liborc-0.4-0
  libpaper-utils libpaper1 libpciaccess0 libpoppler-glib8 libpoppler46 libpostproc52 libproj0 libpulse0 libpython2.7 libqt4-opengl libqtcore4 libqtgui4 libquadmath0 libraw1394-11 librsvg2-2 librsvg2-common libsamplerate0
  libschroedinger-1.0-0 libsfcgal1 libsmbclient libsndfile1 libspatialite5 libspeex1 libswscale3 libtalloc2 libtdb1 libtevent0 libtheora0 liburiparser1 libusb-1.0-0 libv4l-0 libv4lconvert0 libva1 libvcdinfo0 libvdpau1 libvorbis0a
  libvorbisenc2 libvpx1 libwavpack1 libwbclient0 libwebp5 libwmf0.2-7 libx264-142 libxerces-c3.1 libxine2 libxine2-bin libxine2-doc libxine2-ffmpeg libxine2-misc-plugins libxine2-plugins libxvidcore4 mysql-common odbcinst
  odbcinst1debian2 poppler-data postgresql-9.6-postgis-2.3 postgresql-9.6-postgis-2.3-scripts proj-bin proj-data python-talloc qtcore4-l10n samba-libs va-driver-all vdpau-va-driver
0 upgraded, 147 newly installed, 0 to remove and 62 not upgraded.
Need to get 73.2 MB/73.3 MB of archives.
After this operation, 333 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
`

**Comment by sebastic** [comment]
```
apt-get --no-install-recommends <PKG>
```

**Comment by mhugo** [comment]
@sebastic @Komzpa Hi I've just published a 1.3.1 release. Will is be ok for the Debian packages ?

**Comment by sebastic** [comment]
Probably, yes. I'll update the package later today after I get back from work.

It's too late for inclusion in the next stable release (stretch), but will be included in following stable release (buster).

**Comment by sebastic** [comment]
SFCGAL 1.3.1 is now available in stretch-backports for Debian stable users, you can install its libsfcgal1 to get rid of the openscenegraph dependencies (if `--no-install-recommends` wasn't used).

**Comment by mhugo** [comment]
@sebastic Thanks for your work !

**Comment by analytik** [comment]
I'm sorry if this is the wrong place to mention this, but `libsfcgal1=1.3.0-1~bpo8+1` works nicely, but `libsfcgal1=1.3.0-4` installs X11, QT, audio, image, video codecs, a video player and Python. 300MB of trash.

#God bless semver

**Comment by sebastic** [comment]
You should upgrade to stretch and use libsfcgal1 (1.3.1-2~bpo9+1) from stretch-backports which was explicitly backported to allow users of stretch to have a libsfcgal1 without the OpenSceneGraph dependencies.

**Comment by ChristophBerg** [comment]
Fwiw, using stretch-backports along with stretch-pgdg from apt.postgresql.org works:

Plain stretch+stretch-pgdg:
```
$ agi postgresql-9.6-postgis-2.5
Die folgenden NEUEN Pakete werden installiert:
  fontconfig fontconfig-config fonts-dejavu-core libaec0 libarmadillo7 libarpack2 libasound2 libasound2-data libass5 libasyncns0
  libaudio2 libavahi-client3 libavahi-common-data libavahi-common3 libavc1394-0 libavcodec57 libavdevice57 libavfilter6 libavformat57
  libavresample3 libavutil55 libblas-common libblas3 libbluray1 libboost-chrono1.62.0 libboost-date-time1.62.0
  libboost-program-options1.62.0 libboost-serialization1.62.0 libboost-test1.62.0 libboost-thread1.62.0 libboost-timer1.62.0 libbs2b0
  libcaca0 libcairo2 libcdio-cdda1 libcdio-paranoia1 libcdio13 libcgal12 libchromaprint1 libcoin80v5 libcrystalhd3 libcups2 libdap23
  libdapclient6v5 libdapserver7v5 libdatrie1 libdbus-1-3 libdc1394-22 libdrm2 libebur128-1 libegl1-mesa libepsilon1 libfaad2
  libfftw3-double3 libflac8 libflite1 libfontconfig1 libfreetype6 libfreexl1 libfribidi0 libgbm1 libgdal20 libgdk-pixbuf2.0-0
  libgdk-pixbuf2.0-common libgeos-3.5.1 libgeos-c1v5 libgeotiff2 libgfortran3 libgif7 libgl1-mesa-glx libglapi-mesa libgme0
  libgraphicsmagick-q16-3 libgraphite2-3 libgsm1 libharfbuzz0b libhdf4-0-alt libhdf5-100 libice6 libiec61883-0 libiso9660-8
  libjack-jackd2-0 libjbig0 libjpeg62-turbo libjson-c3 libkmlbase1 libkmlconvenience1 libkmldom1 libkmlengine1 libkmlregionator1
  libkmlxsd1 liblapack3 liblcms2-2 libldb1 libltdl7 liblwgeom-2.5-0 libmad0 libmariadbclient18 libminizip1 libmng1 libmodplug1
  libmp3lame0 libmpcdec6 libmpg123-0 libnetcdf11 libnspr4 libnss3 libnuma1 libodbc1 libogdi3.2 libogg0 libopenal-data libopenal1
  libopencv-core2.4v5 libopencv-imgproc2.4v5 libopenjp2-7 libopenmpt0 libopenscenegraph100v5 libopenthreads20 libopus0 libpango-1.0-0
  libpangocairo-1.0-0 libpangoft2-1.0-0 libpgm-5.2-0 libpixman-1-0 libpng16-16 libpoppler-glib8 libpoppler64 libpostproc54 libpq5
  libproj12 libprotobuf-c1 libpulse0 libpython2.7 libqhull7 libqt4-opengl libqtcore4 libqtgui4 libraw1394-11 librsvg2-2 librubberband2
  libsamplerate0 libsdl2-2.0-0 libsfcgal1 libshine3 libslang2 libsm6 libsmbclient libsnappy1v5 libsndfile1 libsndio6.1 libsodium18
  libsoxr0 libspatialite7 libspeex1 libssh-gcrypt-4 libsuperlu5 libswresample2 libswscale4 libsz2 libtalloc2 libtbb2 libtdb1 libtevent0
  libthai-data libthai0 libtheora0 libtiff5 libtwolame0 liburiparser1 libusb-1.0-0 libv4l-0 libv4lconvert0 libva-drm1 libva-x11-1 libva1
  libvcdinfo0 libvdpau1 libvorbis0a libvorbisenc2 libvorbisfile3 libvpx4 libwavpack1 libwayland-client0 libwayland-cursor0
  libwayland-egl1-mesa libwayland-server0 libwbclient0 libwebp6 libwebpmux2 libwmf0.2-7 libwrap0 libx11-6 libx11-data libx11-xcb1
  libx264-148 libx265-95 libxau6 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shape0 libxcb-shm0
  libxcb-sync1 libxcb-xfixes0 libxcb1 libxcursor1 libxdamage1 libxdmcp6 libxerces-c3.1 libxext6 libxfixes3 libxi6 libxine2 libxine2-bin
  libxine2-ffmpeg libxine2-misc-plugins libxine2-plugins libxinerama1 libxkbcommon0 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6
  libxtst6 libxv1 libxvidcore4 libxxf86vm1 libzmq5 libzvbi-common libzvbi0 mysql-common odbcinst odbcinst1debian2 postgresql-9.6
  postgresql-9.6-postgis-2.5 postgresql-client-9.6 proj-data python-talloc qtcore4-l10n samba-libs shared-mime-info x11-common xkb-data
0 aktualisiert, 247 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 107 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 366 MB Plattenplatz zusätzlich benutzt.
```

stretch+stretch-backports+stretch-pgdg:
```
$ agi postgresql-9.6-postgis-2.5 -t stretch-backports
Die folgenden NEUEN Pakete werden installiert:
  fontconfig-config fonts-dejavu-core libaec0 libarmadillo7 libarpack2 libblas-common libblas3 libboost-atomic1.62.0
  libboost-chrono1.62.0 libboost-date-time1.62.0 libboost-program-options1.62.0 libboost-serialization1.62.0 libboost-test1.62.0
  libboost-thread1.62.0 libboost-timer1.62.0 libcgal12 libdap23 libdapclient6v5 libdapserver7v5 libepsilon1 libfontconfig1 libfreetype6
  libfreexl1 libgdal20 libgeos-3.5.1 libgeos-c1v5 libgeotiff2 libgfortran3 libgif7 libhdf4-0-alt libhdf5-100 libjbig0 libjpeg62-turbo
  libjson-c3 libkmlbase1 libkmlconvenience1 libkmldom1 libkmlengine1 libkmlregionator1 libkmlxsd1 liblapack3 liblcms2-2 libltdl7
  liblwgeom-2.5-0 libmariadbclient18 libminizip1 libnetcdf11 libnspr4 libnss3 libodbc1 libogdi3.2 libopenjp2-7 libpng16-16 libpoppler64
  libpq5 libproj12 libprotobuf-c1 libqhull7 libsfcgal1 libspatialite7 libsuperlu5 libsz2 libtiff5 liburiparser1 libwebp6 libxerces-c3.1
  mysql-common odbcinst odbcinst1debian2 postgresql-9.6 postgresql-9.6-postgis-2.5 postgresql-client-9.6 proj-data
0 aktualisiert, 73 neu installiert, 0 zu entfernen und 33 nicht aktualisiert.
Es müssen 36,6 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 136 MB Plattenplatz zusätzlich benutzt.
```
