### ISSUE TITLE
1.3.1 build failure with CGAL 4.10

### ISSUE THREAD

**Issue by ilovezfs** [Oslandia/SFCGAL#142]
Full build log is here: https://gist.github.com/ilovezfs/b0b22d72f42095c3a0cf3c81643b1f7b

The first error is
```
/usr/local/include/CGAL/internal/corefinement/Combinatorial_map_output_builder.h:911:23: error: no type named 'Union_find' in namespace 'CGAL'
      typedef ::CGAL::Union_find<Facet_const_handle> UF;
              ~~~~~~~~^
```
but there are others.

Build failure occurred on Homebrew CI on all 3 boxes (macOS 10.10, 10.11 and 10.12).
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2158/

**Comment by saultdon** [comment]
I can confirm that the build fails on Arch Linux with the same errors.

**Comment by ilovezfs** [comment]
@mhugo have you had a chance to look at this? Thanks!

**Comment by TacomaGranny** [comment]
It also happens on a Mac building from source release. MacOS 10.12

**Comment by ilovezfs** [comment]
@TacomaGranny right that was my original report: "Build failure occurred on Homebrew CI on all 3 boxes (macOS 10.10, 10.11 and 10.12)."

**Comment by ilovezfs** [comment]
@mhugo gentle ping on this as we have a user requesting the 4.10 upgrade in https://github.com/Homebrew/homebrew-core/issues/15387.

**Comment by devrimgunduz** [comment]
Hi,

This is also a blocker for Fedora 26 upgrades :/

**Comment by ilovezfs** [comment]
@lrineau do you have any suggestions here? It might be useful to get some help/guidance from upstream CGAL here since this issue is blocking upgrades of CGAL in both Homebrew and Fedora.

**Comment by lrineau** [comment]
Hi @ilovezfs, and others. I was not aware of the issue. I will investigate...

Actually, `<CGAL/corefinement_operations.h>` is not a documented header, and that explains why our automatic tests have not caught the issue. I have forwarded the issue to @sloriot (author of the header). There is almost certainly a missing `#include`. Sébastien (@sloriot) will prepare a PR against CGAL-4.10. Meanwhile, to workaround the issue, you can add `#include <CGAL/Union_find.h>` in `src/algorithm/Intersection3D.cpp`, before the inclusion of `<CGAL/corefinement_operations.h>`. That will fix the compilation error, if that was the only error.

**Comment by ilovezfs** [comment]
@lrineau after that I see https://gist.github.com/ilovezfs/9a8ab63522591e12e3e9c2adfffa1720

**Comment by sloriot** [comment]
Please see https://github.com/CGAL/cgal/issues/2258

**Comment by ilovezfs** [comment]
@lrineau @sloriot unfortunately, even with the patch, the build of SFCGAL is still failing:

```
[ 27%] Building CXX object src/CMakeFiles/SFCGAL.dir/algorithm/Intersection3D.cpp.o
cd /tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++  -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DCGAL_INTERSECTION_VERSION=1 -DSFCGAL_BUILD_SHARED -DSFCGAL_EXPORTS -I/tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/include -I/tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/patches/CGAL-4.3 -isystem /usr/local/include  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -fPIC   -o CMakeFiles/SFCGAL.dir/algorithm/Intersection3D.cpp.o -c /tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src/algorithm/Intersection3D.cpp
/tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src/algorithm/Intersection3D.cpp:144:19: error: no matching constructor for initialization of 'Split_visitor' (aka 'Node_visitor_refine_polyhedra<Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge>, CGAL::Epeck, Edge_mark_property_map<Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge> > >')
    Split_visitor visitor( NULL, true );
                  ^        ~~~~~~~~~~
/usr/local/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h:512:3: note: candidate constructor not viable: no known conversion from 'long' to 'OutputBuilder' (aka 'CGAL::Epeck') for 1st argument
  Node_visitor_refine_polyhedra (
  ^
/usr/local/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h:309:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class Node_visitor_refine_polyhedra{
      ^
/usr/local/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h:535:20: error: no member named 'input_have_coplanar_facets' in 'CGAL::Epeck'
    output_builder.input_have_coplanar_facets();
    ~~~~~~~~~~~~~~ ^
/usr/local/include/CGAL/intersection_of_Polyhedra_3.h:2031:16: note: in instantiation of member function 'CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::input_have_coplanar_facets' requested here
      visitor->input_have_coplanar_facets();
               ^
/usr/local/include/CGAL/intersection_of_Polyhedra_3.h:2152:12: note: in instantiation of function template specialization 'CGAL::Intersection_of_Polyhedra_3<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>, CGAL::Default, CGAL::Default, CGAL::Default>::main_run<std::__1::back_insert_iterator<std::__1::list<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > >, std::__1::allocator<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > > > > > >' requested here
    return main_run(out);
           ^
/tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src/algorithm/Intersection3D.cpp:152:20: note: in instantiation of function template specialization 'CGAL::Intersection_of_Polyhedra_3<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>, CGAL::Default, CGAL::Default, CGAL::Default>::operator()<std::__1::back_insert_iterator<std::__1::list<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > >, std::__1::allocator<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > > > > > >' requested here
    intersect_polys( polya, polyb, std::back_inserter( polylines ) );
                   ^
In file included from /tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src/algorithm/Intersection3D.cpp:24:
In file included from /usr/local/include/CGAL/intersection_of_Polyhedra_3.h:27:
In file included from /usr/local/include/CGAL/Exact_predicates_exact_constructions_kernel.h:29:
In file included from /usr/local/include/CGAL/Filtered_kernel.h:27:
/usr/local/include/CGAL/Cartesian_converter.h:56:24: error: no type named 'FT' in 'SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >'
  typedef typename K1::FT FT1;
          ~~~~~~~~~~~~~^~
/usr/local/include/CGAL/Cartesian_converter.h:93:49: note: in instantiation of template class 'CGAL::internal::Default_converter<SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Epeck>' requested here
           class Converter = typename internal::Default_converter<K1, K2>::Type >
                                                ^
/usr/local/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h:918:13: note: in instantiation of default argument for 'Cartesian_converter<SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Epeck>' required here
      CGAL::Cartesian_converter<Kernel,Exact_kernel> convert;
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/CGAL/intersection_of_Polyhedra_3.h:2041:16: note: in instantiation of function template specialization 'CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::finalize<CGAL::internal_IOP::Triangle_segment_intersection_points<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Default_polyhedron_ppmap<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Epeck, CGAL::internal_IOP::Predicates_on_constructions, true> >' requested here
      visitor->finalize(nodes);
               ^
/usr/local/include/CGAL/intersection_of_Polyhedra_3.h:2152:12: note: in instantiation of function template specialization 'CGAL::Intersection_of_Polyhedra_3<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>, CGAL::Default, CGAL::Default, CGAL::Default>::main_run<std::__1::back_insert_iterator<std::__1::list<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > >, std::__1::allocator<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > > > > > >' requested here
    return main_run(out);
           ^
/tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src/algorithm/Intersection3D.cpp:152:20: note: in instantiation of function template specialization 'CGAL::Intersection_of_Polyhedra_3<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>, CGAL::Default, CGAL::Default, CGAL::Default>::operator()<std::__1::back_insert_iterator<std::__1::list<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > >, std::__1::allocator<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > > > > > >' requested here
    intersect_polys( polya, polyb, std::back_inserter( polylines ) );
                   ^
In file included from /tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src/algorithm/Intersection3D.cpp:25:
/usr/local/include/CGAL/intersection_of_Polyhedra_3_refinement_visitor.h:1120:5: error: type 'OutputBuilder' (aka 'CGAL::Epeck') does not provide a call operator
    output_builder(border_halfedges, nodes, an_edge_per_polyline, is_node_of_degree_one, polyhedron_to_map_node_to_polyhedron_vertex);
    ^~~~~~~~~~~~~~
/usr/local/include/CGAL/intersection_of_Polyhedra_3.h:2041:16: note: in instantiation of function template specialization 'CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::finalize<CGAL::internal_IOP::Triangle_segment_intersection_points<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Default_polyhedron_ppmap<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Epeck, CGAL::internal_IOP::Predicates_on_constructions, true> >' requested here
      visitor->finalize(nodes);
               ^
/usr/local/include/CGAL/intersection_of_Polyhedra_3.h:2152:12: note: in instantiation of function template specialization 'CGAL::Intersection_of_Polyhedra_3<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>, CGAL::Default, CGAL::Default, CGAL::Default>::main_run<std::__1::back_insert_iterator<std::__1::list<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > >, std::__1::allocator<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > > > > > >' requested here
    return main_run(out);
           ^
/tmp/sfcgal-20170713-608-xelsvj/SFCGAL-1.3.1/src/algorithm/Intersection3D.cpp:152:20: note: in instantiation of function template specialization 'CGAL::Intersection_of_Polyhedra_3<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, SFCGAL::algorithm::Edge_mark_property_map<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, HalfedgeDS_default, std::__1::allocator<int> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>, CGAL::Default, CGAL::Default, CGAL::Default>::operator()<std::__1::back_insert_iterator<std::__1::list<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > >, std::__1::allocator<std::__1::vector<CGAL::Point_3<CGAL::Epeck>, std::__1::allocator<CGAL::Point_3<CGAL::Epeck> > > > > > >' requested here
    intersect_polys( polya, polyb, std::back_inserter( polylines ) );
                   ^
4 errors generated.
make[2]: *** [src/CMakeFiles/SFCGAL.dir/algorithm/Intersection3D.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/SFCGAL.dir/all] Error 2
make: *** [all] Error 2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make install
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Comment by lrineau** [comment]
It seems SFCGAL has used a lot of non-documented code of CGAL, that has been modified in an incompatible way in recent CGAL versions. We (you, us) should discuss with the upstream of SFCGAL (Oslandia) and try to find a solution with them.

**Comment by ilovezfs** [comment]
CC @ldgeo @mhugo @ocourtin @vpicavet

**Comment by mhugo** [comment]
@lrineau @sloriot thanks for your help. I think, since we are using mostly headers from CGAL and no cpp (I still have to check), we could ship SFCGAL with a version of CGAL headers known to work ...
That would avoid this kind of problems in the future and simplify some hacks (https://github.com/Oslandia/SFCGAL/tree/master/patches)

**Comment by sloriot** [comment]
Note that since CGAL-4.10 corefinement has an official API. However, I don't remember if it will be able to solve all your problems.
See [here](doc.cgal.org/latest/Polygon_mesh_processing/group__PMP__corefinement__grp.html)

**Comment by lrineau** [comment]
Sébastien meant here: [section *Corefinement and Boolean Operations* in the *Polygon Mesh Processing* chapter][1].

  [1]: http://doc.cgal.org/4.10/Polygon_mesh_processing/group__PMP__corefinement__grp.html

**Comment by ilovezfs** [comment]
It doesn't appear to be headers only
```
iMac-TMP:homebrew-core joe$ brew linkage sfcgal
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/opt/boost/lib/libboost_atomic-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_chrono-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_date_time-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_serialization-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_system-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_thread-mt.dylib (boost)
  /usr/local/opt/cgal/lib/libCGAL.12.dylib (cgal)
  /usr/local/opt/cgal/lib/libCGAL_Core.12.dylib (cgal)
  /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)
  /usr/local/opt/mpfr/lib/libmpfr.4.dylib (mpfr)
iMac-TMP:homebrew-core joe$ brew linkage --reverse sfcgal
/usr/lib/libSystem.B.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/lib/libc++.1.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/boost/lib/libboost_atomic-mt.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/boost/lib/libboost_chrono-mt.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/boost/lib/libboost_date_time-mt.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/boost/lib/libboost_serialization-mt.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/boost/lib/libboost_system-mt.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/boost/lib/libboost_thread-mt.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/cgal/lib/libCGAL.12.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/cgal/lib/libCGAL_Core.12.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/gmp/lib/libgmp.10.dylib
  lib/libSFCGAL.1.3.1.dylib

/usr/local/opt/mpfr/lib/libmpfr.4.dylib
  lib/libSFCGAL.1.3.1.dylib
```

**Comment by devrimgunduz** [comment]
Hi,

Any progress with this? Thanks!

**Comment by devrimgunduz** [comment]
ping.

**Comment by vmora** [comment]
@devrimgunduz pong, I'm going to have a look.

**Comment by devrimgunduz** [comment]
Thanks @vmora .

**Comment by vmora** [comment]
There is only one function that causes the compilation issue: SFCGAL/src/algorithm/Intersection3D.cpp:141:
```
void _intersection_solid_triangle( const MarkedPolyhedron& pa, const CGAL::Triangle_3<Kernel>& tri, GeometrySet<3>& output )
```

I'll try and see if all the tests pass (except those using this function).

The diff is big in the [branch above](https://github.com/Oslandia/SFCGAL/commit/4580a6ff0f558b407a8d8b558f0e9adb1d2539af) because I use the opportunity to remove auto_ptr deprecation warnings.

@lrineau, @sloriot is there a simple way to compute triangle/polyhedron intersection ?

**Comment by sloriot** [comment]
do you mean the intersection of surfaces or somehow triangle+volume?

**Comment by vmora** [comment]
@sloriot I mean the intersection of a triangle and a volume.

**Comment by sloriot** [comment]
The simplest way to do it would be to create a polyhedron for the triangle and call `corefine_and_compute_intersection()`.

**Comment by vmora** [comment]
Reading from the doc, the 2 input meshes should define a volume, and a triangle is an open surface.

**Comment by sloriot** [comment]
yes but it will work.

**Comment by vmora** [comment]
@sloriot on `corefine_and_compute_intersection(poly_a, poly_b, poly_out)` I get:
```
CGAL/Polygon_mesh_processing/internal/Corefinement/Face_graph_output_builder.h:453:35: error: no matching function for call to ‘get(const bool&, CGAL::HDS_graph_traits<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge> >::face_descriptor)’
```

**Comment by sloriot** [comment]
If you polyhedron type does not have a default face index map you need to pass one. For example add as fourth parameter:
```
CGAL::Polygon_mesh_processing::parameters::face_index_map(get(CGAL::face_external_index, poly_a))
```
and as fifth parameter:
```
CGAL::Polygon_mesh_processing::parameters::face_index_map(get(CGAL::face_external_index, poly_b))
```

**Comment by vmora** [comment]
@sloriot hanks, it fails a bit further now (I think):
```
 /usr/local/include/CGAL/Kernel/function_objects.h:2044:7: error: no match for ‘operator!=’ (operand types are ‘CGAL::cpp11::result_of<CGAL::CommonKernelFunctors::Intersect_3<CGAL::Simple_cartesian<CGAL::Gmpq> >(CGAL::Plane_3<CGAL::Simple_cartesian<CGAL::Gmpq> >, CGAL::Line_3<CGAL::Simple_cartesian<CGAL::Gmpq> >)>::type {aka CGAL::Object}’ and ‘const boost::none_t’)
       CGAL_assertion(res!=boost::none);
```
and I'm still at loss.

**Comment by sloriot** [comment]
I suspect you have some old backward compatibility flags define. Something link `CGAL_INTERSECTION_VERSION`. Am I correct?

**Comment by vmora** [comment]
You are right. Trying without that... thanks for that @sloriot

**Comment by vmora** [comment]
@sloriot it compiles fine now, thanks. But the unit test fails, and the result of the corefine_and_compute_intersection result looks correct when a triangle intersects the bulk of a cube, but not when it lies on a face of a cube. Is it expected or not ?

I'm also wondering about what I should expect in the result when the intersection between the cube and the triangle is a point/line, will the output contain vertex/half-edge and not face ?

**Comment by sloriot** [comment]
Coplanarity should not be an issue. But since the output is expected to fit inside a polyhedron non-degree 2 tangency will not be reported. I guess you use to have a dedicated piece of code to handle that. Now that I'm thinking more about it, the whole cube might be reported if the triangle is oriented as the cube. Is it what you are getting?

**Comment by vmora** [comment]
>  the whole cube might be reported if the triangle is oriented as the cube. Is it what you are getting?

nope, triangle on face -> nothing in output, point tangent -> nothing in output. 

I'll try and have a deeper look into the existing code, and test some edge-case of corefine_and_compute_intersection, but it's not something I can solve easily. 

@ilovezfs, @saultdon what are the "dealines" for release ?

**Comment by saultdon** [comment]
@vmora For myself, it's needed as a dependency for the postgis-sfcgal package in the Arch Linux AUR. As a rolling release the package is ready when upstream (here) is ready =) So no hard deadline.

**Comment by devrimgunduz** [comment]
@vmora : Fedora 26 was released last month, which is shipped with CGAL 4.10, and upgrade path from F-25 is currently broken -- so we need a patch/release asap, please :-)

Regards, Devrim

**Comment by ilovezfs** [comment]
@vmora same situation as Arch as Homebrew is also rolling release. We've chosen to block the CGAL 4.10 upgrade indefinitely pending resolution of this issue.

**Comment by devrimgunduz** [comment]
Is there a patch that we can test?

**Comment by devrimgunduz** [comment]
Hi,

Sorry for pestering you, but this is blocking and breaking upgrades :(

Regards, Devrim

**Comment by vmora** [comment]
@devrimgunduz sorry, I haven't been able to find a solution. There is no easy fix and the culprit function has to be re-written, which is not trivial (at least for me).

For the moment we are looking for a solution to allocate resources to solve this problem. If people are interested in funding the work, this would definitely help.

**Comment by devrimgunduz** [comment]
@vmora I asked for help on Twitter. Do you have an estimate of the amount of the funding required?

**Comment by lbartoletti** [comment]
On FreeBSD, we are currently with CGAL 3.9. I have done a test and I have the same error when compiling SFCGAL with CGAL 3.10.
I'll talk to the CGAL maintainer about it.

**Comment by vmora** [comment]
@devrimgunduz we will have a look into that later this week, until then, difficult to estimate the time it will take (anything between a couple of hour and a couple of weeks ;)

**Comment by devrimgunduz** [comment]
@vmora ok I need to know the amount :)

**Comment by vmora** [comment]
@devrimgunduz we had a minisprint this morning with @sloriot and fixed the compilation issue (you can checkout the branch mentioned above). So it was more a couple of hours that a couple thanks to him.

Unfortunately the tests don't pass because of a bug in some arcane part of CGAL that we are using, @sloriot is working on it.

**Comment by mhugo** [comment]
@devrimgunduz @ilovezfs @saultdon @lbartoletti 
Here is the release branch with the fix for an upcoming 1.3.2:
https://github.com/Oslandia/SFCGAL/tree/1.3.x

Could you test and confirm it compiles with CGAL 4.10 ?

Unit tests won't pass with 4.10. There is still a small bug that will be fixed in CGAL 4.10.1 (coming hopefully at the end of the day)

**Comment by devrimgunduz** [comment]
@mhugo It fails on Fedora 26:

https://gist.github.com/devrimgunduz/c00390b6f215c9effeadfd898ea8795e

It might be GCC 7 issue as well.

**Comment by ilovezfs** [comment]
Same deal on macOS with clang: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8245/version=sierra/console

**Comment by ilovezfs** [comment]
It does build against https://github.com/CGAL/cgal/tree/releases/CGAL-4.10-branch successfully, though :)

**Comment by ilovezfs** [comment]
@devrimgunduz can you confirm it's OK on Fedora with the tip of releases/CGAL-4.10-branch and/or 4.11beta1?

**Comment by devrimgunduz** [comment]
@ilovezfs can you elaborate, please?

**Comment by ilovezfs** [comment]
@devrimgunduz I saw the same build failure you identified in https://gist.github.com/devrimgunduz/c00390b6f215c9effeadfd898ea8795e when I built with the 4.10 release. However, when I built with the top of the git branch "releases/CGAL-4.10-branch", things were fine. I'm assuming that will be true on Linux too, but was hoping you could confirm that is indeed the case.

**Comment by devrimgunduz** [comment]
@ilovezfs Are you talking about CGAL or SFCGAL? I cannot touch CGAL, as we use the library included in the OS while building RPMS.

If you are talking about SFCGAL, then I'm using fix_cgal-4.10 branch, right?

Thanks!

**Comment by devrimgunduz** [comment]
FWIW, fix_cgal-4.10 branch is still failing.

**Comment by ilovezfs** [comment]
I'm talking about the CGAL branch releases/CGAL-4.10-branch. But if you cannot change CGAL, then you cannot test that I guess :)

**Comment by devrimgunduz** [comment]
:/ 

Just checked, Fedora 27 will ship with CGAL 4.11, but it does not solve the current problem :(

**Comment by ilovezfs** [comment]
And you're testing https://github.com/Oslandia/SFCGAL/tree/1.3.x + CGAL 4.11?

**Comment by ilovezfs** [comment]
@mhugo 4.10.1 was tagged https://github.com/CGAL/cgal/releases/tag/releases%2FCGAL-4.10.1. Are there any other blockers for a new SFCGAL release now with the fix from https://github.com/Oslandia/SFCGAL/tree/1.3.x?

**Comment by ilovezfs** [comment]
@devrimgunduz will Fedora 26 be upgraded to CGAL 4.10.1?

**Comment by lrineau** [comment]
@ilovezfs I have created the update today: https://bodhi.fedoraproject.org/updates/FEDORA-2017-cc4956b3aa and it should be in the Fedora repo `updates-testing` today or tomorrow, and the `updates` in less than two weeks.

**Comment by ilovezfs** [comment]
@lrineau nice! You're too quick for me :)

**Comment by lrineau** [comment]
That was easy for me: I am at the same time the CGAL release manager, and the maintainer of the CGAL rpm packages in Fedora.

**Comment by mhugo** [comment]
@lrineau thanks for the 4.10.1 release.
I will tag a 1.3.2

**Comment by mhugo** [comment]
Done https://github.com/Oslandia/SFCGAL/releases/tag/v1.3.2

**Comment by ilovezfs** [comment]
Thanks @mhugo! PR for 1.3.2 in Homebrew: https://github.com/Homebrew/homebrew-core/pull/18034.

I think we're done here :)

**Comment by devrimgunduz** [comment]
\o/ Thanks everyone who solved this issue. All clear from my side, too!

Thanks @mhugo , @ilovezfs @lrineau @vmora and others!

**Comment by vmora** [comment]
Thanks @sloriot !
