### ISSUE TITLE
ST_3DDifference crashes 

### ISSUE THREAD

**Issue by Edward1984** [Oslandia/SFCGAL#150]
Hello,
with this query (basically i'm trying the command on two "simple" linestrings)

**with 
geom1 as (
select St_GeomFromText('LINESTRING Z (309296.0018 4877451.6848 1,309296.4817 4877451.1948 1,309295.4017 4877450.1548 1)') as geom
), 
geom2 as (
select St_GeomFromText('LINESTRING Z (309295.4017 4877450.1548 1,309292.0518 4877446.9148 0.9)') as geom
)
select ST_3DDifference(geom1.geom, geom2.geom) from geom1, geom2**

I have this error:

DEBUG:  StartTransactionCommand
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
LOG:  istruzione: 
with 
geom1 as (
select St_GeomFromText('LINESTRING Z (309296.0018 4877451.6848 1,309296.4817 4877451.1948 1,309295.4017 4877450.1548 1)') as geom
), 
geom2 as (
select St_GeomFromText('LINESTRING Z (309295.4017 4877450.1548 1,309292.0518 4877446.9148 0.9)') as geom
)
select ST_3DDifference(geom1.geom, geom2.geom) from geom1, geom2
DEBUG:  [lwgeom_ogc.c:LWGEOM_from_text:789] LWGEOM_from_text
DEBUG:  [lwgeom_ogc.c:LWGEOM_from_text:790] wkt: [LINESTRING Z (309296.0018 4877451.6848 1,309296.4817 4877451.1948 1,309295.4017 4877450.1548 1)]
DEBUG:  [lwin_wkt.c:wkt_parser_ptarray_new:307] entered
DEBUG:  [lwin_wkt.c:wkt_parser_ptarray_add_coord:268] entered
********** Error **********

Connection lost!!

This is testing with SFCGAL 1.3.0

**Comment by mhugo** [comment]
Can't reproduce on last master
