### ISSUE TITLE
Build from source with custom CGAL_DIRECTORY

### ISSUE THREAD

**Issue by jhiemer** [Oslandia/SFCGAL#151]
Hey, 
this might perhaps seem like a stupid question, but I am currently trying to build SFCGAL from scratch for Postgis. As the deployment will be rolled out with Bosh (deployment orchestrator for CF and K8s), I have to stick to some specific directory structures:

CGAL 4.9 

```shell 
BOSH_INSTALL_TARGET=/var/vcap/packages/cgal
VERSION=4.9
tar -xvzf cgal/cgal-releases-CGAL-${VERSION}.tar.gz
cd cgal-releases-CGAL-${VERSION}/

export BOOST_ROOT=/var/vcap/packages/boost
export GMP_DIR=/var/vcap/packages/gmp
export MPFR_DIR=/var/vcap/packages/mpfr

cmake -DCMAKE_INSTALL_PREFIX=$BOSH_INSTALL_TARGET -DCMAKE_BUILD_TYPE=Release .
make
make install
```

CGAL executes successfully. When I try to build SFCGAL with the following parameters:

SFCGAL 1.3.0

```shell
VERSION=1.3.0
tar -xvzf postgis/SFCGAL-${VERSION}.tar.gz
cd SFCGAL-${VERSION}/

export BOOST_ROOT=/var/vcap/packages/boost
export GMP_DIR=/var/vcap/packages/gmp
export MPFR_DIR=/var/vcap/packages/mpfr
export CGAL_DIR=/var/vcap/packages/cgal

cmake -DCMAKE_INSTALL_PREFIX=$BOSH_INSTALL_TARGET .
make
make install
```
I always run in the the following:

```shell
, Stderr: + VERSION=1.3.0
+ tar -xvzf postgis/SFCGAL-1.3.0.tar.gz
+ cd SFCGAL-1.3.0/
+ export BOOST_ROOT=/var/vcap/packages/boost
+ BOOST_ROOT=/var/vcap/packages/boost
+ export GMP_DIR=/var/vcap/packages/gmp
+ GMP_DIR=/var/vcap/packages/gmp
+ export MPFR_DIR=/var/vcap/packages/mpfr
+ MPFR_DIR=/var/vcap/packages/mpfr
+ export CGAL_DIR=/var/vcap/packages/cgal/lib/x86_64-linux-gnu/CGAL
+ CGAL_DIR=/var/vcap/packages/cgal/lib/x86_64-linux-gnu/CGAL
+ export CGAL_LIBRARIES=/var/vcap/packages/cgal/lib/x86_64-linux-gnu/CGAL
+ CGAL_LIBRARIES=/var/vcap/packages/cgal/lib/x86_64-linux-gnu/CGAL
+ export CGAL_Core_LIBRARY=/var/vcap/packages/cgal/lib/x86_64-linux-gnu/CGAL
+ CGAL_Core_LIBRARY=/var/vcap/packages/cgal/lib/x86_64-linux-gnu/CGAL
+ cmake -DCMAKE_INSTALL_PREFIX=/var/vcap/packages/sfcgal .
CGAL_DIR
CMake Error at cmake/Modules/FindCGAL.cmake:29 (file):
  file STRINGS file
  "/var/vcap/data/compile/sfcgal/SFCGAL-1.3.0/version_file-NOTFOUND" cannot
  be read.
Call Stack (most recent call first):
  CMakeLists.txt:115 (find_package)


CMake Error at cmake/Modules/FindCGAL.cmake:30 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:115 (find_package)


CMake Error at cmake/Modules/FindCGAL.cmake:32 (message):
  CGAL 4.3 is required (found in version_file-NOTFOUND)
Call Stack (most recent call first):
  CMakeLists.txt:115 (find_package)
```

**Comment by sloriot** [comment]
... **where** the file `CGALConfig.cmake` is installed

**Comment by handoyog** [comment]
Hi..
For SFCGAL-1.3.0 or SFCGAL-1.3.x, I am also experiencing the same thing :

CGALConfig.cmake is located in /usr/lib/cgal/lib/CGAL

But even setting -DCGAL_DIR=/usr/lib/cgal/lib/CGAL
does not solve the problem. CMake still unable to find where CGAL is.

@lrineau : Are you sure that CGAL_DIR is the variable that CMake is using ?

**Comment by sloriot** [comment]
@handoyog did you remove the local FindCGAL.cmake?

**Comment by handoyog** [comment]
@sloriot : No, I didn't remove it. All I have been trying to do is compiling without removing or altering.

However, browsing FindCGAL.cmake, I found out that this code : 
===============
find_path(CGAL_INCLUDE_DIRS CGAL/gmp.h
       HINTS $ENV{CGAL_DIR}/include ${CGAL_DIR}/include ${CGAL_INCLUDE_DIRS}
       PATH SUFFIXES CGAL
)
===============

After I specify CGAL_INCLUDE_DIRS, it seems cmake works, but now coming with a different Warning :

WARNING: Target "SFCGAL" request linking to directory "/usr/lib/cgal/lib/CGAL". Targets may link only to libraries. CMake is dropping the item.
-- Generating done
-- Build files have been written to /export/home/myuser/GIS/SFCGAL/SFCGAL-1.3.x

Which .cmake file is this location of linking located ? Cause proceeding with 'gmake' fails at 98%, where this linking is about to happens

**Comment by handoyog** [comment]
Furthermore, 
# ldd libSFCCGAL.so 
turns out the : libCGAL.so.13  => ( file not found )

is this caused by the Warning above unable to find where CGAL is

**Comment by sloriot** [comment]
Could you try with the latest version and tell if you still have the issue?

**Comment by sloriot** [comment]
Note that `CGAL_DIR` must point to the directory containing `CGALConfig.cmake`

**Comment by robe2** [comment]
I'm getting this error too.  It seems the last version of sfcgal I can compile without this error is 1.3.4.

I compared 1.3.4 with 1.3.8 and I noticed these lines were taken out:

``
find_package( GMP )
if( ${GMP_FOUND} )
	message( STATUS "GMP_INCLUDE_DIRS = ${GMP_INCLUDE_DIRS}" )
	message( STATUS "GMP_LIBRARIES = ${GMP_LIBRARIES}" )
	set( SFCGAL_WITH_GMP ON )
endif()

#-- MPFR (needs GMP)  --------------------------------------
if( ${GMP_FOUND} )
	find_package( MPFR )
	if( ${MPFR_FOUND} )
		message( STATUS "MPFR_INCLUDE_DIRS = ${MPFR_INCLUDE_DIRS}" )
		message( STATUS "MPFR_LIBRARIES = ${MPFR_LIBRARIES}" )
		set( SFCGAL_WITH_MPFR ON )
	endif()
endif()

if( NOT ${GMP_FOUND} OR NOT ${MPFR_FOUND} )
	message( WARNING "can't find GMP and MPFR, using default kernel" ) 
	set( EPLU_USE_CARTESIAN_KERNEL ON )
endif()

``

What was the reason for removing them?  Unfortunately it seems if I try to pass those in in CMake it says it won't be used.  I'm compiling against CGAL 4.11
