### ISSUE TITLE
no matching function for call to ‘__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(CGAL::Gmpz, const long int&)’

### ISSUE THREAD

**Issue by strk** [Oslandia/SFCGAL#152]
Master branch (5499795d00fea8b6b8fe8991bf8799b9e3b1805c) fails to build against libcgal-4.9-1 as packaged in Ubuntu 17.04

Compiler is g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

error is: 
> [  1%] Building CXX object src/CMakeFiles/SFCGAL.dir/Coordinate.cpp.o
/usr/src/sfcgal/sfcgal/src/Coordinate.cpp: In member function ‘CGAL::Lazy_kernel_generic_base<CGAL::Simple_cartesian<CGAL::Gmpq>, CGAL::Simple_cartesian<CGAL::Interval_nt<false> >, CGAL::Cartesian_converter<CGAL::Simple_cartesian<CGAL::Gmpq>, CGAL::Simple_cartesian<CGAL::Interval_nt<false> > >, CGAL::Epeck>::FT SFCGAL::RoundVisitor::_roundFT(const FT&) const’:
/usr/src/sfcgal/sfcgal/src/Coordinate.cpp:273:28: error: no matching function for call to ‘__gmp_expr<__mpq_struct [1], __mpq_struct [1]>::__gmp_expr(CGAL::Gmpz, const long int&)’
                            ) ) ;
                            ^

**Comment by strk** [comment]
Tag v1.3.0 builds fine

**Comment by vmora** [comment]
@strk thanks, on it.

**Comment by sebastic** [comment]
This error was also reported in #145, work on the GMPXX changes (#149) has stalled.

**Comment by mhugo** [comment]
Would someone has the opportunity to test the new branch https://github.com/Oslandia/SFCGAL/tree/bundled that should fix the problem ?

**Comment by sebastic** [comment]
Embedded code copies, really?

Instead of including CGAL in SFCGAL, wouldn't it be better for SFCGAL to be part of the CGAL project?

**Comment by sloriot** [comment]
I think most of the issues where due to usage of undocumented CGAL code (that is now hopefully documented) + issues with the cmake scripts. I also feel like future upgrade of CGAL should no longer break anything for SFCGAL.

**Comment by sebastic** [comment]
SFCGAL 1.3.5 indeed did not break with the recent update of CGAL to 4.13 in Debian unstable.

**Comment by mhugo** [comment]
@sebastic @sloriot Thanks for your feedback. So are we are waiting for packagers to use CGAL 4.13 ...

**Comment by lbartoletti** [comment]
can we close this ticket?

**Comment by strk** [comment]
Good to me
