### ISSUE TITLE
How to find out if 2 polygons are fully contained in the other one (no partial overlap)?

### ISSUE THREAD

**Issue by danfran** [Oslandia/SFCGAL#154]
Hi, I was going through the code:

https://github.com/Oslandia/SFCGAL/blob/master/src/algorithm/intersects.cpp

in the function:

`bool _intersects( const PrimitiveHandle<2>& pa, const PrimitiveHandle<2>& pb )`

and I can see that for "Polygon vs Polygon" the intersection happens if two polygons intersect or one contains the other one.

On the current *C API* is there anyway to find out if  one polygon *only* contains another polygon (not intersections with partial overlap)? 

Of course unless of checking if any single vertex of one polygon is in the other polygon.

In my specific case I need something like 

`if (A is contained in B) {....} else if (A intersects B) {...} else {...}`

Thank you!

**Comment by mhugo** [comment]
There is currently no way to test if a polygon is contained in another one.

A covers() method exists in the C++ API, but is not recommended since it uses a very naive implementation based on the computation of an intersection.
