### ISSUE TITLE
3D ST_MinkowskiSum

### ISSUE THREAD

**Issue by MBunel** [Oslandia/SFCGAL#156]
Hello,

In [this conversation](http://osgeo-org.1560.x6.nabble.com/Calculating-a-buffer-in-n-dimmension-tp5142377p5142468.html) an implementation of the minkosky sum usable with 3d geometries is mentioned, but I do not find any mention of it in the documentation, the API or even the code of sfcgal.

Has this function been removed from the library ? Can I use it by downgrading my postgis ?

Best

**Comment by mhugo** [comment]
Well, I may have spoken too fast :/
3D minkowski sums exists in CGAL. But only on Nef polyhedra, which we do not use anymore in SFCGAL for ages. Sorry only 2D here.
