### ISSUE TITLE
SFCGAL_CHECK_VALIDITY seems to be away, but still in doc

### ISSUE THREAD

**Issue by nicklasaven** [Oslandia/SFCGAL#164]
It seems like the functionality to avoid validity check is ripped out with 
https://github.com/Oslandia/SFCGAL/commit/14b8a13852f2268a3867a089f158cacceaa0b7fa#diff-af3b638bc2a3e6c650974192a53c7291

But in the doc about installation options there is still an option:
http://oslandia.github.io/SFCGAL/installation.html

Is there some other undocumented way of avoiding the validity check?
Or is the docs just behind?

**Comment by mhugo** [comment]
You should now sets the validity flag on geometries.
The doc has been updated. Thanks
