### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by fxcoudert** [Oslandia/SFCGAL#172]
Hi, at Homebrew we are having many failures for our users on `scfgal`, which in turn impacts `postgis`. It appears there have been some fixes to build with recent cgal and boost, but they are not in a released version. Would you please consider making a point release (1.3.6) so we can ship that?

Thanks!

**Comment by fxcoudert** [comment]
It was working for a time, but now it's broken again. This time it's https://github.com/Oslandia/SFCGAL/issues/188

At this point it appears that `sfcgal` is not kept in sync with CGAL, and it's been blocking us several times from updating to newer versions of the software. Do you have plans for a fix for latest CGAL? Otherwise I'll propose removal of SFCGAL from Homebrew.

**Comment by lbartoletti** [comment]
Will be fixed with the next release.

**Comment by lbartoletti** [comment]
There is a new release and homebrew is already updated :)
I close this issue
