### ISSUE TITLE
Replace auto_ptr by unique_ptr

### ISSUE THREAD

**Issue by mhugo** [Oslandia/SFCGAL#175]
That will need a new major version since auto_ptr are used in the C++ api

**Comment by danielcu888** [comment]
This issue looks complete with no references to `std::auto_ptr` in the source code (thanks btw!). There are three comments that mistakenly reference `std::auto_ptr`, which I have updated in my PR (rf https://github.com/Oslandia/SFCGAL/pull/213).

**Comment by mhugo** [comment]
Indeed, thanks for the fix @danielcu888
