### ISSUE TITLE
Installation creates both (prefix)/lib AND (prefix)/lib64

### ISSUE THREAD

**Issue by zerothi** [Oslandia/SFCGAL#210]
When installing on certain OS's one may have default library locations in lib64 sub-folders.

In that case the build system of SFCGAL does this:

0. Run `cmake -DCMAKE_INSTALL_PREFIX=<PREFIX>`
1. Create `<PREFIX>/lib/libSFCGAL.la`
2. Put all libraries in `<PREFIX>/lib64/lib*.{so,a}`

This is not conforming since `*.la` contains information about library placement (and is incorrect).

**Comment by lbartoletti** [comment]
FYI libtool control was removed by https://github.com/Oslandia/SFCGAL/pull/223

Is this issue still present?
