### ISSUE TITLE
Could not find a configuration file for package "CGAL" on SFCGAL-1.3.7

### ISSUE THREAD

**Issue by jongguheo** [Oslandia/SFCGAL#229]
Hello
I'm encountering an error. If you know how to solve it please help me.

Error is like this.
[/opt/SFCGAL-1.3.7]# /opt/cmake3.12.3/bin/cmake -DCMAKE_INSTALL_PREFIX=/opt/sfcgal -DCGAL_DIR=/opt/cgal/lib64/cmake/CGAL
CMake Error at CMakeLists.txt:59 (find_package):
  Could not find a configuration file for package "CGAL" that is compatible
  with requested version "4.3".

  The following configuration files were considered but not accepted:
  /opt/cgal/lib64/cmake/CGAL/CGALConfig.cmake, version: unknown

-- Configuring incomplete, errors occurred!
See also "/opt/SFCGAL-1.3.7/CMakeFiles/CMakeOutput.log".

What is the problem...?
My environment is like.

$ /opt/cmake3.12.3/bin/cmake --version
cmake version 3.12.3

CGAL root directory.
/opt/cgal]# ls
include  lib64  share

CGAL Version is 5.0.2. Installation way is 
1. tar -xvf cgal-releases-CGAL-5.0.2.tar.gz
2. cd cgal-releases-CGAL-5.0.2/
3. mkdir build && cd build
4. /opt/cmake3.12.3/bin/cmake -DCMAKE_BUILD_TYPE=Release 
-DCMAKE_INSTALL_PREFIX=/opt/cgal  ..
5. make && make install

**Comment by lrineau** [comment]
CGAL has a merged pull-request addressing that issue: https://github.com/CGAL/cgal/pull/4697. It will be in CGAL-4.14.4 and CGAL-5.0.3.

**Comment by jongguheo** [comment]
Thank you for your reply! I have reinstalled the CGAL with 4.14 version. It works.
