### ISSUE TITLE
straight skeleton time dimension

### ISSUE THREAD

**Issue by hjanetzek** [Oslandia/SFCGAL#35]
Hi,
I'm trying to use ST_StraigthSkeleton for building roofs and I figured that one has to find the shortest distance trough the skeleton to get the proper height for roof ridges. Looking into CGAL the vertices provide a time value which seems provides the information. Would it be possible to have a ST_StraightSkeleton3D which provides time as z or m dimension?

http://doc.cgal.org/latest/Straight_skeleton_2/classStraightSkeletonVertex__2.html

(An example for a complex hipped roof build with SFCGAL :)
http://opensciencemap.org/~jeff/test/#scale=17,rot=326,tilt=57,lat=48.855,lon=2.312)

**Comment by mhugo** [comment]
Added an option to straightSkeleton to output distance to border as M coordinate

**Comment by Remi-C** [comment]
great !

2016-02-25 18:25 GMT+01:00 Hugo Mercier <notifications@github.com>:
