### ISSUE TITLE
State of sfcgal_triangulate in PostGIS

### ISSUE THREAD

**Issue by hjanetzek** [Oslandia/SFCGAL#36]
Is there a reason why lwgeom_sfcgal already includes the code for triangulate_2dz but it is not (yet) exported with with sfcgal.sql?

**Comment by tomvantilburg** [comment]
This would still be a nice feature to have available from postgis. Afaik there are 2 functions that already do triangulation but in different ways. ST_DelaunayTriangulation is unconstrained, only does points and drops the Z while ST_Tesselate only does polygons.

I have it running as st_triangulate2dz, and up to now without bugs.
To activate it in postgis:
```
CREATE OR REPLACE FUNCTION st_triangulate2dz(geometry)
  RETURNS geometry AS
'$libdir/postgis-2.3', 'sfcgal_triangulate'
  LANGUAGE c IMMUTABLE STRICT
  COST 100;
```

**Comment by Komzpa** [comment]
PostGIS ticket:
https://trac.osgeo.org/postgis/ticket/4198

**Comment by lbartoletti** [comment]
ST_ConstrainedDelaunayTriangles (sfcgal.triangulate_2dz) is available in Postgis
