### ISSUE TITLE
viewer Cmake sources globbing pulls CMakeCXXCompilerId.cpp in

### ISSUE THREAD

**Issue by giohappy** [Oslandia/SFCGAL#58]
Reading on the web file globbing with GLOB_RECURSE is considered evil for this reason.
GLOB on single directories would be fine. In case recursion wants be mantained the cmake generated .cpp file must be removed from sources list like I do here: https://github.com/giohappy/SFCGAL/blob/fix_cmake_globbing/viewer/CMakeLists.txt#L16

In case it is ok for you I will submit a pull, but imho using per directory globbing should be cleaner

**Comment by mhugo** [comment]
Viewer is not part of SFCGAL core anymore
