### ISSUE TITLE
Ability to omit components touching boundary from StraightSkeleton output

### ISSUE THREAD

**Issue by strk** [Oslandia/SFCGAL#76]
Would a patch adding a parameter to omit lines that touch the input polygon boundary from StraightSkeleton output be accepted ? It'd be aimed at providing an approximate "MedialAxis" implementation.

**Comment by Remi-C** [comment]
It would be super cool tout have an option to output not only the lines of
the sskeleton,
but also fort each line its connectivity degree regarding the boundary.
For instance touching boundary are 0 lines.
Touching 0 lines are lines 1, etc.

You could do what you want, but with much more flexibility
Cheers
Remic
Le 10 juin 2015 09:44, "Sandro Santilli" <notifications@github.com> a
écrit :

**Comment by vmora** [comment]
@strk Where do you want to put the parameter, in the C API ? 

I'd rather go for an additional function, approximateMedialAxis sounds like a nice name.

**Comment by vmora** [comment]
Remi-C I think the output format for this info is a bit tricky (an M coord ??). Outputting a graph would be nice... but it(s not in SFS, is it ?

@strk If I understand http://doc.cgal.org/latest/Straight_skeleton_2/index.html correctly, filtering out edges that are less than N edges from the border shouldn't cost anything but adding a counter to straightSkeletonToMultiLineString and ressetting it on it->is_bisector(). Not sure about the duplicate filtering in this case though.

**Comment by Remi-C** [comment]
Tricky?
you can either put it in M, or also output an array of int that relates to
each line, without creating a custom type.

Nothing to complicated I would think.

About graph, of course I could build such a graph and compute myself the
information, but why spend computing time for something we may already
easily have.

Only removing line touching boundary is not going to give a valid median
axis in many common situation, thus if you want the function to be of any
use with real world data, some more information would be nice.

Cheers,
Rémi-C

2015-06-10 18:29 GMT+02:00 Vincent Mora <notifications@github.com>:

**Comment by vmora** [comment]
Remi-C, I find "tricky" to choose the right (most usable) output format among what you propose and others: It could be, e.g. an array of multilinestrings, where the index is the distance from the boundary, a geometrycollection of multylinestrings would do the trick too.

Do you have a preference for one of those ?

When I was mentioning a graph, I was not thinking about recomputing it, but actually having the straigthSkeleton output the graph it has internally instead of converting it to multilinestring. The problem beeing, again, to define the output type.

**Comment by Remi-C** [comment]
Hmm I realy like the geom collection,  because if you don't care about the
order, you simply use st_collectionextract.

Graph might be difficult to output. Maybe with topogeomjson, in a second
time.
Cheers
Remic

**Comment by mhugo** [comment]
When we are at extending the straight skeleton, I think the issue #35 is related. With a Z or M dimension to represent the "time" of each vertex, it would be very useful for generation of building roofs.
About the output format : the geometry collection ordered by logical distance to the boundary seems nice. Do you see any problem with it ?

**Comment by Remi-C** [comment]
For me : perfect.
Cheers
Remi c

**Comment by strk** [comment]
I'm working on approximateMedialAxis. Question: is it acceptable to modify the ABI of the C++ interface ?
I'm thinking about adding an "innerOnly" parameter to the straightSkeleton, defaulting to false.

**Comment by strk** [comment]
For reference, last time that ABI was touched was with  8cedb443ee1cb46edd595f3a01b4f51940626b43 in April 23 2013, commit which mentions a reference of ``#161`` that cannot be a github issue.. do you know what it is ?

**Comment by strk** [comment]
Actually, I found a later break with 2c0c3c1c14d01ebf3afba52a2800bc01885cf86e (June 21 2013) which added the variant not checking for validity

**Comment by strk** [comment]
Implementation specific comments can go to the PR I just filed: #85

**Comment by strk** [comment]
This is completed. It took another signature to maintain C-API.
