### ISSUE TITLE
Update NEWS file to 1.1.0

### ISSUE THREAD

**Issue by strk** [Oslandia/SFCGAL#84]
The latest release advertised in NEWS file is 1.0.5, but latest release is 1.1.0 according to https://github.com/Oslandia/SFCGAL/releases

**Comment by strk** [comment]
Another discrepancy is that the download link from the project website still points at 1.0.5: 
http://oslandia.github.io/SFCGAL/dev.html -- so now I'm wondering if 1.1.0 is a real thing. Is it ?

\cc @vmora, @ocourtin

**Comment by vmora** [comment]
Yes, I hadn't had time to update the web page yet.

**Comment by strk** [comment]
PR fixing this is ready: #88
