### ISSUE TITLE
benchmark tests do not rebuild on core library headers change

### ISSUE THREAD

**Issue by strk** [Oslandia/SFCGAL#86]
I've noticed that changing the ABI of the core library, while retaining API compatibility, raises errors on building the benchmarks. Evidently they do not get rebuilt when the core library headers are changed.

Forcing a rebuild they do get the new definitions and build correctly.

**Comment by mhugo** [comment]
I can't reproduce: when modifying for instance area.h, then the BenchArea.cpp is rebuilt ...

**Comment by danielcu888** [comment]
Can this still be reproduced? If not can this ticket be closed?

**Comment by lbartoletti** [comment]
Are you ok to close this (old) issue @strk ?

**Comment by strk** [comment]
Yes, ok.
