### ISSUE TITLE
Robustness issue with StraightSkeleton and inexact construction kernel 

### ISSUE THREAD

**Issue by strk** [Oslandia/SFCGAL#89]
Looking at the StraightSkeleton for the input reported in ticket #80 reveals a robustness issue that results in a piece of skeleton falling outside the input polygon, see:

![skeleton_inexact_kernel](https://cloud.githubusercontent.com/assets/289678/8184924/785c2434-1441-11e5-81c8-38c4a6997a90.png)

The artifact goes away if the input polygon is first translated to have 0,0 as its lowest-left point and the output skeleton is translated back to its original position, see:

![skeleton_inexact_kernel_shifted](https://cloud.githubusercontent.com/assets/289678/8184946/9d54629c-1441-11e5-8092-b5da18db94c2.png)

The skeleton computed with "extact construction" kernel is otherwise visually equal to the one computed with the improved robusness (shifting). Running the translation doesn't significantly affect performances.

Maybe this issue should be reported upstream to CGAL..

**Comment by strk** [comment]
\cc @vmora, @mhugo

**Comment by strk** [comment]
Simplified input still reproducing the robustness issue:
```
POLYGON((1686350.74365082 5402217.7661505,1684030.810026 5402682.520688,1684000 5402672.31399816,1683763.966259 5402588.179891,1681281.134295 5403807.881624,1683915.838219 5402676.741864,1684000 5402711.41802501,1684020.618162 5402719.913077,1687524.6533522 5404490.5663652,1687854.358551 5403919.598884,1686350.74365082 5402217.7661505))
```

**Comment by strk** [comment]
Filed upstream here: https://github.com/CGAL/cgal/issues/123

**Comment by strk** [comment]
I guess I could implement the polygon translation in SFCGAL, but it'd be best done after pr #85 is merged

**Comment by strk** [comment]
Translating a Polygon_with_holes_2 is revealing harder than I hoped for. It'd be a pity to clone the input Geometry just for the sake of translating, am I missing an easy way to do that ?

**Comment by drewish** [comment]
It's probably not the issue but worth double checking the vertex ordering. I forget which it wants but I was getting back 0,0 points. Reversing the direction fixed that. If you're only getting that one point that's wrong it might be an totally different issue.

**Comment by strk** [comment]
Single point out, and fixed by augmenting the available bits for computation (shifting to origin)

**Comment by vmora** [comment]
It looks like the problematic vertex joins two aligned segments. If it's really the case, then maybe joining aligned ring segment would fix things.

I don't mind gaining precision/robustness by moving vtx near origin, but this alignment, considering the definition of a straight skeleton bugs me a little.

**Comment by strk** [comment]
You can check it by running ST_Simplify on the input with a tolerance of 0.
If that fixes, it could maybe be worth doing this upstream, see
https://github.com/CGAL/cgal/issues/123

**Comment by strk** [comment]
Here's the HEXWKB format for the offending polygon input as I just found out that parsing it from WKT makes the problem go away:
```
010300002091080000010000000A00000063022B0A53C139419EFCD3EF4E9B54412DDD5DCF3EB23941C4F352A10E9C54410400000020B23941C08B18140C9C544116E9B9D592A739410DA9B7E75A9B54413B28612281A7394113876CF8279D54413C8595D6CBB1394125B37A2F0D9C54410400000020B23941F9EBC0DA159C544168DD3F9E34B2394184DA6FFA179C5441524F641C54C13941C3874722D79D544163022B0A53C139419EFCD3EF4E9B5441
```

Any way to have SFCGAL parse WKB for writing the testcase ?

**Comment by strk** [comment]
about the aligned segments idea, this simple polygon does not trigger the problem:
``POLYGON((0 0, 10 0, 10 10, 5 10, 0 10, 0 0))``

**Comment by strk** [comment]
Also passing the input polygon trough ST_Simplify() with a tolerance of 1e-10 does not remove the "almost collinear" vertex. A tolerance of 1e-9 does, fixing the problem.
